### Soal 1

In [2]:
import numpy as np

a = [[[[23, 50], [7, 12]], [[57, 67], [99, 43]]], [[[75, 21], [57, 12]], [[87, 26],[18, 84]]]]
ten_a = np.array(a)
print(a)

[[[[23, 50], [7, 12]], [[57, 67], [99, 43]]], [[[75, 21], [57, 12]], [[87, 26], [18, 84]]]]


### Soal 2

In [3]:
a = [[23, 50, 19], [7, 12, 109], [57, 67, 98]]
b = [[17], [22], [19]]
mat_a = np.array(a)
mat_b = np.array(b)

# A * B
print(mat_a @ mat_b)

[[1852]
 [2454]
 [4305]]


### Soal 3

In [7]:
a = [[23, 50, 19], [7, 12, 109], [57, 67, 98]]
mat_a = np.array(a)

#Transpose matrix a
tran_a = mat_a.transpose()
print(tran_a)

#Determinant matrix a
det_a = np.linalg.det(mat_a)
print(round(det_a))

#Inverse matrix a
inv_a = np.linalg.inv(mat_a)
print(inv_a)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]
131344
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
